FROM nginx:alpine

COPY index.html    /usr/share/nginx/html/index.html
COPY checkin.html  /usr/share/nginx/html/checkin.html
COPY log.html      /usr/share/nginx/html/log.html
COPY css/          /usr/share/nginx/html/css/
COPY js/           /usr/share/nginx/html/js/

EXPOSE 80
